lemmatization module
catebi/FreeganBot pull request #17
Opened 2023-12-14 16:17 UTC by Gregr1G

2023-12-14 18:41 UTC, lejafo commented
а можно было бы добавить юнит-тесты на это дело?

2023-12-14 20:03 UTC, religofsil requested changes
без #18 велика вероятность проблем с запуском

2023-12-14 21:23 UTC, religofsil requested changes
Убери, пожалуйста, лишние использования lower, особенно в main.py? эта функция уже есть в process_text(), её не нужно применять больше одного раза.

2023-12-14 21:24 UTC, religofsil requested changes
Убери, пожалуйста, лишние использования lower, особенно в main.py? эта функция уже есть в process_text(), её не нужно применять больше одного раза.

2023-12-14 21:26 UTC, religofsil requested changes
модуль лемматизации должен убрать необходимость обращения к модулю re, его не нужно импортировать и не нужно использовать в 42 строке

2023-12-14 21:29 UTC, religofsil requested changes
функция process_text сейчас возвращает весь текст, сджойненный по пробелам;
если мы хотим искать пересечения со списком ключевых слов, нужно, чтобы она возвращала множество (set) слов в тексте

2023-12-15 08:17 UTC, religofsil approved these changes

2023-12-15 08:18 UTC, religofsil commented
я не всё хотела аппрувить, но лан, можем вынести остальное в отдельную ишью
@lejafo как думаешь, как лучше?

2023-12-15 09:04 UTC, lejafo commented
> я не всё хотела аппрувить, но лан, можем вынести остальное в отдельную ишью @lejafo как думаешь, как лучше?

мне кажется, да можно. если оно сейчас работает и перечислены необходимые либы в requirements, давайте пушнем в мэйн

2023-12-15 09:17 UTC, lejafo approved these changes

2023-12-15 11:01 UTC, lejafo commented
@Gregr1G как будет возможность, смерджи пр

2023-12-15 15:28 UTC, merged